Map_query_casillas_2025 = '''

SELECT 
    C.SECCION AS SECCION, 
    SUM(C.MC) AS MC,
    SUM(C.PVEM + C.MOR + C.C_PVEM_MOR) AS MORENA_PVEM,  
    SUM(C.PAN) AS PAN, 
    SUM(C.PRI) AS PRI, 
    SUM(C.PT) AS PT, 
    SUM(C.TOTAL_VOTOS_ASENTADO) AS TOTAL_VOTOS, 
    SUM(C.LISTA_NOMINAL) AS NOMINAL, 
    P.POBLACION
FROM 
    casillas_2025 C
LEFT JOIN (
    SELECT SECCION, GROUP_CONCAT(DISTINCT POBLACION) AS POBLACION
    FROM Poblaciones
    GROUP BY SECCION
) P ON C.SECCION = P.SECCION
WHERE 
    C.SECCION = ?
GROUP BY 
    C.SECCION

'''

Map_query_casillas_2021 = '''

SELECT 
    C.SECCION AS SECCION, 
    SUM(MC) AS MC,  
    SUM(MOR) AS MORENA,
    SUM(PT) AS PT,
    SUM(PVEM) AS PVEM,
    SUM(TODOS) AS TODOS,
    SUM(PAN + PRI +PRD  ) AS PAN_PRI_PRD, 
    SUM(PODEMOS) AS PODEMOS,
    SUM(CARDENISTA) AS CARDENISTA,
    SUM(UNIDAD) AS UNIDAD,
    SUM(RSP) AS RSP,
    SUM(FM) AS FM,
    SUM(TOTAL_VOTOS_ASENTADO) AS TOTAL_VOTOS, 
    SUM(LISTA_NOMINAL) AS NOMINAL
FROM 
    casillas_2021 C

WHERE 
    C.SECCION = ?
GROUP BY 
    C.SECCION

'''