Map_query_casillas_2025 = '''

SELECT 
    C.SECCION AS SECCION, 
    SUM(C.MC) AS MC,
    SUM(C.PVEM + C.MOR + C.C_PVEM_MOR) AS MORENA_PVEM,  
    SUM(C.PAN) AS PAN, 
    SUM(C.PRI) AS PRI, 
    SUM(C.PT) AS PT, 
    SUM(C.TOTAL_VOTOS_ASENTADO) AS TOTAL_VOTOS, 
    SUM(C.LISTA_NOMINAL) AS NOMINAL, 
    P.POBLACION
FROM 
    casillas_2025 C
LEFT JOIN (
    SELECT SECCION, GROUP_CONCAT(DISTINCT POBLACION) AS POBLACION
    FROM Poblaciones
    GROUP BY SECCION
) P ON C.SECCION = P.SECCION
WHERE 
    C.SECCION = ?
GROUP BY 
    C.SECCION

'''

Map_query_casillas_2021 = '''

SELECT 
    C.SECCION AS SECCION, 
    SUM(MC) AS MC,  
    SUM(MOR) AS MORENA,
    SUM(PT) AS PT,
    SUM(PVEM) AS PVEM,
    SUM(TODOS) AS TODOS,
    SUM(PAN + PRI +PRD  ) AS PAN_PRI_PRD, 
    SUM(PODEMOS) AS PODEMOS,
    SUM(CARDENISTA) AS CARDENISTA,
    SUM(UNIDAD) AS UNIDAD,
    SUM(RSP) AS RSP,
    SUM(FM) AS FM,
    SUM(TOTAL_VOTOS_ASENTADO) AS TOTAL_VOTOS, 
    SUM(LISTA_NOMINAL) AS NOMINAL
FROM 
    casillas_2021 C

WHERE 
    C.SECCION = ?
GROUP BY 
    C.SECCION

'''

Map_query_casillas_2017 = '''

SELECT 
    C.SECCION AS SECCION, 
    SUM(C_PAN_PRD + PAN  +  PRD) AS PAN_PRD,
    SUM(C_PRI_PVEM +  PRI + PVEM) AS C_PRI_PVEM,
    SUM(MORENA) AS MORENA,
    SUM(NUEVA_ALIANZA) AS NUEVA_ALIANZA,
    SUM(MOVIMIENTO_CIUDADANO) AS MC,
    SUM(PT) AS PT,
    SUM(ES) AS ES,
    SUM(TOTAL_VOTOS) AS TOTAL_VOTOS, 
    SUM(LISTA_NOMINAL) AS NOMINAL
FROM 
    casillas_2017 C

WHERE 
    C.SECCION = ?
GROUP BY 
    C.SECCION

'''

Totals_2025 = '''

SELECT 
    MUNICIPIO,
    ID_MUNICIPIO, 
    SUM(C.MC) AS MC,
    SUM(C.PVEM + C.MOR + C.C_PVEM_MOR) AS MORENA_PVEM,  
    SUM(C.PAN) AS PAN, 
    SUM(C.PRI) AS PRI, 
    SUM(C.PT) AS PT, 
    SUM(C.TOTAL_VOTOS_ASENTADO) AS TOTAL_VOTOS, 
    SUM(C.LISTA_NOMINAL) AS NOMINAL
FROM 
    casillas_2025 C
WHERE 
    C.ID_MUNICIPIO = ?
GROUP BY 
    MUNICIPIO, C.ID_MUNICIPIO

'''

Totals_2021 = '''

SELECT 
    MUNICIPIO,
    ID_MUNICIPIO,
    SUM(MC) AS MC,  
    SUM(MOR) AS MORENA,
    SUM(PT) AS PT,
    SUM(PVEM) AS PVEM,
    SUM(TODOS) AS TODOS,
    SUM(PAN + PRI +PRD) AS PAN_PRI_PRD, 
    SUM(PODEMOS) AS PODEMOS,
    SUM(CARDENISTA) AS CARDENISTA,
    SUM(UNIDAD) AS UNIDAD,
    SUM(RSP) AS RSP,
    SUM(FM) AS FM,
    SUM(TOTAL_VOTOS_ASENTADO) AS TOTAL_VOTOS, 
    SUM(LISTA_NOMINAL) AS NOMINAL
FROM 
    casillas_2021 C
WHERE 
    C.ID_MUNICIPIO = ?
GROUP BY 
    MUNICIPIO, C.ID_MUNICIPIO

'''