Map_query = '''

SELECT 
    C.SECCION AS SECCION, 
    SUM(MC) AS MC,
    SUM(PVEM + MOR + C_PVEM_MOR) AS MORENA,  
    SUM(PAN) AS PAN, 
    SUM(PRI) AS PRI, 
    SUM(PT) AS PT, 
    SUM(TOTAL_VOTOS_ASENTADO) AS TOTAL_VOTOS, 
    SUM(LISTA_NOMINAL) AS NOMINAL, 
    GROUP_CONCAT(DISTINCT P.POBLACION) AS POBLACION
FROM 
    casillas C
LEFT JOIN 
    Poblaciones P ON C.SECCION = P.SECCION
WHERE 
    C.SECCION = ?
GROUP BY 
    C.SECCION

'''