import pandas as pd
import sqlite3

# Cargar el CSV
df = pd.read_csv("Result_Catemaco_2021_.csv")

# Limpiar campos clave (por ejemplo, quitar comillas y espacios de SECCION)
df["SECCION"] = df["SECCION"].astype(str).str.replace("'", "").str.strip()

# Conectarse o crear la base de datos
conn = sqlite3.connect("catemaco_2025.db")
cursor = conn.cursor()

# Eliminar la tabla si ya existe
cursor.execute("DROP TABLE IF EXISTS casillas_2021")

# Crear tabla con campos específicos
cursor.execute("""
CREATE TABLE casillas_2021 (
CLAVE_CASILLA TEXT,
CLAVE_ACTA TEXT,
ID_ESTADO INTEGER,
ESTADO TEXT,
ID_MUNICIPIO INTEGER,
MUNICIPIO TEXT,
SECCION INTEGER,
ID_CASILLA INTEGER,
TIPO_CASILLA TEXT,
EXT_CONTIGUA TEXT,
UBICACION_CASILLA TEXT,
TIPO_ACTA TEXT,
TOTAL_BOLETAS_SOBRANTES INTEGER,
TOTAL_PERSONAS_VOTARON INTEGER,
TOTAL_REP_PARTIDO_CI_VOTARON INTEGER,
TOTAL_VOTOS_SACADOS INTEGER,
PAN INTEGER,
PRI INTEGER,
PRD INTEGER,
PVEM INTEGER,
PT INTEGER,
MC INTEGER,
MOR INTEGER,
TODOS INTEGER,
PODEMOS INTEGER,
CARDENISTA INTEGER,
UNIDAD INTEGER,
PES INTEGER,
RSP INTEGER,
FM INTEGER,
CAND_IND_1 INTEGER,
CAND_IND_2 INTEGER,
C_PAN_PRI_PRD INTEGER,
C_PAN_PRI INTEGER,
C_PAN_PRD INTEGER,
C_PRI_PRD INTEGER,
C_PVEM_PT_MOR INTEGER,
C_PVEM_PT INTEGER,
C_PVEM_MOR INTEGER,
C_PT_MOR INTEGER,
NO_REGISTRADOS INTEGER,
NULOS INTEGER,
TOTAL_VOTOS_ASENTADO INTEGER,
TOTAL_VOTOS_CALCULADO INTEGER,
LISTA_NOMINAL INTEGER,
REPRESENTANTES_PP_CI INTEGER,
OBSERVACIONES TEXT,
CONTABILIZADA TEXT,
MECANISMOS_TRASLADO TEXT,
SHA TEXT, 
FECHA_HORA_ACOPIO TEXT,
FECHA_HORA_CAPTURA TEXT,
FECHA_HORA_VERIFICACION TEXT,
ORIGEN TEXT,
DIGITALIZACION TEXT,
TIPO_DOCUMENTO TEXT
)
""")

# Insertar los datos
df.to_sql("casillas_2021", conn, if_exists="append", index=False)

# Cerrar conexión
conn.commit()
conn.close()

print("Base de datos creada con éxito: catemaco.db")
